### ISSUE TITLE
Storybooks 3 vs @kadira/storybook-addons

### ISSUE THREAD

**Issue by eugene1g** [truffls/storybook-addon-intl#1]
Hi,

Thanks for the addon. It currently references `@kadira/storybook-addons` - any chance to change it to V3 `@storybook/addons`? This might mean bumping the addon version and make it compatible with Storybooks 3

**Comment by floriangosse** [comment]
Sure, this was our plan. :-)
I will give you an update when this is done.

**Comment by sthuber90** [comment]
Any idea or estimated release date for your new version yet? :)

**Comment by floriangosse** [comment]
I will work on it on this weekend. :-)

**Comment by floriangosse** [comment]
Version 2 was released right now. Please try it out and file an issue if something doesn't work like expected. :)
