### ISSUE TITLE
Make 'LocaleBar' more responsive

### ISSUE THREAD

**Issue by matteocng** [truffls/storybook-addon-intl#10]
When resizing the storybook window and having multiple locales active (i.e 10) one has to use the horizontal scrollbar to see all the locale buttons in `LocaleBar`. It may be nice to use a media query OOB (default value could be `(min-width: 0px) and (max-width: 575px)`?) to apply something like `flex-wrap: wrap;` to `LocaleBar`, so that almost all the buttons would be visible without having to scroll.

**Comment by floriangosse** [comment]
Thank you for this hint. We never had the problem because we only handling two languages but it makes totally sense. 

I will publish a new version which contains the change in a few days and I will notify you. :)

**Comment by floriangosse** [comment]
Finally I had the time.

The new published version [v2.1.2](https://github.com/truffls/storybook-addon-intl/releases/tag/v2.1.2) contains a fix for the locale buttons.
