### ISSUE TITLE
Getting it work with Enzyme 

### ISSUE THREAD

**Issue by simtechmedia** [truffls/storybook-addon-intl#11]
I'm trying to implement storybook-addon-intl with Enzyme for testing, I can get them to work independently but when I try to get them together I get this error

[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

Anyone have this issue? Cheers

**Comment by simtechmedia** [comment]
As outlined on the storyboards documentation on interaction testing

https://storybook.js.org/testing/interaction-testing/

**Comment by floriangosse** [comment]
Thanks and sorry for the late response.

I'm not using the enzyme and storybook together. So I have to set up the environment for it. Could you get a fix for your problem and create a PR for it?

**Comment by floriangosse** [comment]
Since there was no more activity in this issue I close it.
