### ISSUE TITLE
Use the new framework API?

### ISSUE THREAD

**Issue by jonniebigodes** [truffls/storybook-addon-intl#113]
Hey fellow maintainers 👋 !
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. I'm opening up this issue and letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Looking forward to hearing from you and hopefully getting his addon updated as well for 7.0.

Hope everyone has a fantastic day.

Stay safe

**Comment by floriangosse** [comment]
Thanks for your message. I have it on my list but didn't have the time to work on it. 😅 

I will try to work on it over the next few weeks so hopefully it will be ready at the same time Storybook 7 comes out.

**Comment by JReinhold** [comment]
Hey @floriangosse, I'm not trying to stress you out at all, I just want to let you know that, Storybook v7.0.0 is out. It's only on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

If you hit any issues with v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

You're also free to reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen

**Comment by mnigh** [comment]
> Hi @JReinhold. I'm currently working on the migration. Last thing that's missing is a bit of polishing and clean up.
> 
> I will probably publish a new version until the end of the week. I'll let you know. :)

Greetings @floriangosse and thanks for creating this addon! The devs over at [GCTC-NTGC/gc-digital-talent](https://github.com/GCTC-NTGC/gc-digital-talent) appreciate your work as we use it for our multilingual project. We are hoping to upgrade soon to Storybook v7: is there anything we can do to help get you over the finish line for Storybook v7 compatibility?

**Comment by floriangosse** [comment]
I've just published a new version. Please check it out! 🚀 

I'm happy I finally had the time to work on it. 😅
