### ISSUE TITLE
Missing `defaultRichTextElements` i18n configuration prop

### ISSUE THREAD

**Issue by mnigh** [truffls/storybook-addon-intl#118]
# Issue
Would be great to be able to access the `defaultRichTextElements` prop as it was previously available as of v2.4.1.

## References
- https://formatjs.io/docs/react-intl/components/#intlprovider
- https://formatjs.io/docs/react-intl/components/#defaultrichtextelements

**Comment by floriangosse** [comment]
Good point. Will check how we can support more of the default provider props.

**Comment by mnigh** [comment]
> Good point. Will check how we can support more of the default provider props.

@floriangosse We (@esizer and I) have worked on a PR for adding `defaultRichTextElements` #119. Let me know if you have any questions and if not, looking forward to the next release with it!

**Comment by floriangosse** [comment]
Thanks for submitting the PR. I've merged it and will release a new version.
