### ISSUE TITLE
How to access `intl` prop ?

### ISSUE THREAD

**Issue by stefanorg** [truffls/storybook-addon-intl#14]
Hi, in my components i use intlShape's functions by access intl prop, like this:

```
<div>
            <p>{intl.formatMessage({key: 'hi', defaultMessage: 'Hi'})}</p>
            <button>
                <FormattedMessage id="button.label" />
                
            </button>
        </div>
```

There is a way to access the formatMessage function of intlShape interface?

Thanks

**Comment by gerhr** [comment]
Your question should be referenced to *react-intl* repo, not this one. Pls read this [React context](https://reactjs.org/docs/context.html#how-to-use-context) official docs:
then you would understand that `intlShape` should be passed to `.contextTypes` not `.propTypes`

```javascript
import  { injectIntl, intlShape } from "react-intl"

// ...
yourComponent.contextTypes: {
    intl: intlShape
}

export default inject injectIntl(yourComponent)
```

**Comment by stefanorg** [comment]
Hi, thanks for reply.
You are right, but i got confused about injectIntl.

The injectIntl, put the intl in `this.props`. The IntlProvider wrapper otherwise put intl in context.

If i want to be able to use this addon i need to use the context becouse the injectInt is not usable in storybook's stories.

**Comment by floriangosse** [comment]
Hi @stefanorg. You're right the addon provides the context via `<IntlProvider />`  which we provide in a decorator. But everything should work like it is documented in the documentation of `react-intl`.

We use `injectIntl` at a few places and we don't have any problems to render these components in Storybook.

**Comment by floriangosse** [comment]
We use `injectIntl` like it's described in the [documentation](https://github.com/yahoo/react-intl/wiki/API#injection-api).

But we try to avoid `injectIntl` and use the components to render the messages.

**Comment by stefanorg** [comment]
Yes, 

with a .config.js file like this:
```

import React from 'react';
import { addDecorator, configure } from '@storybook/react';
import { setIntlConfig, withIntl } from 'storybook-addon-intl';

import { addLocaleData, IntlProvider } from 'react-intl';
import enLocaleData from 'react-intl/locale-data/en';
import itLocaleData from 'react-intl/locale-data/it';

import itMessages from '../src/language/it.json';
import enMessages from '../src/language/en.json';

import 'antd/dist/antd.css';

addLocaleData(enLocaleData);
addLocaleData(itLocaleData);

const messages = {
    'en': enMessages,
    'it': itMessages
};

const getMessages = (locale) => messages[locale];

// Set intl configuration
setIntlConfig({
  locales: ['en', 'it'],
  defaultLocale: 'it',
  getMessages
});

// Register decorator
addDecorator(withIntl);

const req = require.context('../src/stories', true, /\.stories\.js$/)
function loadStories() {
  req.keys().forEach((filename) => req(filename))
}

configure(loadStories, module);
```

and a components wrapped with `injectIntl` the story is not working, because the Addon provide the intl only by context:

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { injectIntl, FormattedMessage } from 'react-intl';
const ButtonWithInjectIntl = ({intl}) => injectIntl(
       <button>
                <FormattedMessage id="button.label" />
                console.log("formatted:", intl.formatMessage({id:"button.label"})); <-- This is not working
            </button>
);

storiesOf('Button', module)
    .add('Default', () => (
        <div>
            <ButtonWithInjectIntl />
        </div>
    ));
```

So if i want to write a story of a component using the `react-intl` addon, i've to be sure that my component access the `intl` function by context and not by props, otherwise i get errors.
Is this the correct way, right?

**Comment by floriangosse** [comment]
Ok, I think I know the mistake: You're using `injectIntl` inside of the render function of your component. To make `injectIntl` work correctly you have to wrap your component with it. Here is an example:
```
const Button = ({ props }) => (
  return (
    {/* ... */}
  );
);

const ButtonWithInjectIntl = injectIntl(Button);
```

**Comment by stefanorg** [comment]
Great!!! That was the issue :1st_place_medal: 
Thanks :+1:

**Comment by floriangosse** [comment]
I'm happy that I could help you. 😃
