### ISSUE TITLE
Hook to programatically update locale

### ISSUE THREAD

**Issue by baohouse** [truffls/storybook-addon-intl#17]
Is there a way to trigger the locale change on the I18nProvider through my component's onChange handler?

**Comment by baohouse** [comment]
```
import React from 'react';
import { action } from '@storybook/addon-actions';
import addons from '@storybook/addons';
import { storiesOf } from '@storybook/react';

import Footer from './Footer';

const channel = addons.getChannel();
channel.on('intl/set_locale', (locale) => console.log('Heard set locale', locale));

const changeLocale = (locale) => {
  channel.emit('intl/set_locale', locale);
};

storiesOf('Footer', module)
  .add('View', () => (
    <Footer onChange={changeLocale} />
  ));

```

Tried this, I could hear the set locale event when I click on the buttons in the panel. But if I try to trigger it off my component and emit the set locale event, it doesn't seem to do anything.

**Comment by baohouse** [comment]
It works if I edit LocalePanel

```
class LocalePanel extends React.Component {
    constructor (props) {
        super(props);

        this.state = {
            locales: [],
            activeLocale: null
        };

        this.setConfig = this.setConfig.bind(this);
        this.getLocale = this.getLocale.bind(this);
        this.handleClickLocaleButton = this.handleClickLocaleButton.bind(this);

        this.props.channel.on(EVENT_SET_CONFIG_ID, this.setConfig);
        this.props.channel.on(EVENT_GET_LOCALE_ID, this.getLocale);
        this.props.channel.on(EVENT_SET_LOCALE_ID, this.handleClickLocaleButton);
    }
```

Is this okay to do?

**Comment by baohouse** [comment]
Okay, I'm starting to understand how channels work. When you emit an event, it only goes to the "other side"; in other words, if you're inside of the manager, the event will be heard by the preview side, and vice versa.

But if we want to trigger a change from a component inside that would also update the IntlProvider inside WithIntl (all of them being on the preview side), either we expose an updateLocale method inside of the React context. _Or_ we can emit a intl/set_locale event from preview to manager side that will then itself emit the same intl/set_locale event from manager to preview side (and hence, updating the IntlProvider).

The former approach seems cleaner; the latter approach seems like we risk running into infinite loop somewhere in the future.

**Comment by floriangosse** [comment]
That's an interesting and standard use case and I'm wondering why I didn't stumble about it. Thank you! :)

I think we could introduce a change event which the manager could listen to and trigger the set event as a response to it. We could provide the event emitter via context or via a component with a render function. I like the latter more because it's more flexible. I will check out a solution and write here for an update.

P.S.: Sorry for the late response – we have busy weeks.

**Comment by ValentinH** [comment]
Sorry to be that guy... But any update on this? 😄 

I'm also looking for a way to set the locale from my code.

**Comment by floriangosse** [comment]
I'm so sorry – I lost track of it. Currently I don't have to time to create a first draft for it. If one of you could create PR for it that would be really nice. 🙂
