### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [truffls/storybook-addon-intl#184]
Hey @floriangosse! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by floriangosse** [comment]
Thanks for letting me know. I had a first look into the migration guide and I think I should have to update the add-on in the next two weeks. I'll keep you updated about the progress. :)

**Comment by joevaugh4n** [comment]
hey @floriangosse – thank you for this! yeah. let me know how you get on. we’re targeting the full release of SB8 for March 11!

**Comment by schen-fn** [comment]
Hi, can I get a progress update? This is blocking me from updating to StoryBook 8 and would love to update ASAP

**Comment by floriangosse** [comment]
Hey everyone, I'm on that topic right now. But unfortunately the Storybook API doesn't behave as expected and I've opened an issue (https://github.com/storybookjs/storybook/issues/26598). As soon as this is sorted out I'll be able to publish a new version. I'll keep you update in this issue.
