### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by ricca509** [truffls/storybook-addon-intl#20]
Hi,
I'm using storybook 3.4.7, storybook-addon-intl 2.3.0. 
I've added the config as per the example but when running storybook I get the error below:
```
Failed prop type: Invalid prop `children` of type `function` supplied to `IntlProvider`, expected a single ReactElement.
    in IntlProvider (created by WithIntl)
    in WithIntl
```

Is there something I'm missing?

**Comment by floriangosse** [comment]
Hi @ricca509, thanks for reaching us. Do you have the code of a story which causes the problem? And what decorators do you use in addition?

**Comment by ricca509** [comment]
Hey @floriangosse, thanks for the speedy response.
I've put together a testing repo where I reproduced the error: https://github.com/ricca509/test-storybook-intl.
I'm using `withInfo` as additional decorator.

Hope it helps

**Comment by floriangosse** [comment]
Thanks for the reference code. I think the problem might be the usage of `withInfo` because it has to be registered via `.addDecorator()`. You can check it out in the [documentation](https://github.com/storybooks/storybook/tree/master/addons/info#basic-usage] of the info add-on.

**Comment by ricca509** [comment]
I played with it a little bit more and the problem seems to be unrelated to `WithIntl`.
Regardless of how I use `withInfo` (global or per file/with or without `withIntl`) it doesn't work.

Closing this issue as it is not with this module.

Thanks for the support!
