### ISSUE TITLE
Support for Storybook 4

### ISSUE THREAD

**Issue by soundyogi** [truffls/storybook-addon-intl#22]
This seems to be a common problem with the new storybook version:
```Uncaught Error: Accessing nonexistent addons channel```

**Comment by floriangosse** [comment]
Which version of storybook do you use? We use `alpha.14` and don't have any problem.

**Comment by soundyogi** [comment]
Thanks for the fast answer and it is good to know it works for you that means there is hope, this add-on channel thing has not been exaclty easy.

I know this is not really the right place but I dont really know what to do at this point:

deleted node_modules
deleted package-lock.json

all storybook packages I use:
```
    "@storybook/cli": "^4.0.0-alpha.14",
    "@storybook/react": "^4.0.0-alpha.14",
    "@storybook/addons": "^3.4.10",
    "storybook-addon-intl": "^2.3.0",
    "@storybook/addon-knobs": "^4.0.0-alpha.14",
```

.addons.js:
```
import '@babel/polyfill';
import '@storybook/addon-knobs/register';
import 'storybook-addon-intl/register';
```

result:
```Uncaught Error: Accessing nonexistent addons channel,```

(It works with only the knobs-addon)

Did I miss something obvious?

THANKS FOR THE HELP!

**Comment by floriangosse** [comment]
Try to remove `@storybook/addons` from your dependencies. It shouldn't be needed because all addons should define the dependency by themself.

**Comment by soundyogi** [comment]
IT WORKS!

You are my hero.
Am I stupid? Shouldnt this be written somewhere?
I would have never thougth about that.

Time to write my own addon to understand this.

THANKS. SO. MUCH.

**Comment by floriangosse** [comment]
I'm happy that I could help you. :)
