### ISSUE TITLE
Update to work with Storybook 4

### ISSUE THREAD

**Issue by ssylvia** [truffls/storybook-addon-intl#23]
When using with Storybook v4, the language switcher is added to every panel. See image below:

<img width="500" alt="screen shot 2018-09-01 at 9 07 35 am" src="https://user-images.githubusercontent.com/1211360/44946234-86b5ee80-adc6-11e8-8074-ed91b693cc58.png">

**Comment by floriangosse** [comment]
Thanks for the report. I will check what the problem is. Maybe an API changed.
