### ISSUE TITLE
no locale buttons on side bar

### ISSUE THREAD

**Issue by diablourbano** [truffls/storybook-addon-intl#3]
I'm not being able to visualize the [en] [de] buttons displayed on the README screenshot, even I follow the instructions, is anything extra I should do?

**Comment by floriangosse** [comment]
Hi. Do you see any error in the DevTools console?

**Comment by floriangosse** [comment]
The config file would be nice. Thank you. :-)

**Comment by diablourbano** [comment]
@floriangosse sorry for the delay

```
import { configure, setAddon, addDecorator } from '@storybook/react';

import { setOptions } from '@storybook/addon-options';
import infoAddon, { setDefaults } from '@storybook/addon-info';

import { setIntlConfig, withIntl } from 'storybook-addon-intl/dist/preview';
import { addLocaleData } from 'react-intl';
import enLocaleData from 'react-intl/locale-data/en';
import deLocaleData from 'react-intl/locale-data/de';

// addon-options
// https://github.com/storybooks/storybook/tree/master/addons/options
setOptions({
  name: 'Gustav Styleguide',
  url: 'https://github.com/hellogustav/gustav-enroll-frontend',
  showLeftPanel: true,
  showDownPanel: false,
  sortStoriesByKind: false,
});

setAddon(infoAddon);

// storybook-addon-intl
addLocaleData(enLocaleData);
addLocaleData(deLocaleData);

const messages = {
  'en': { 'button.label': 'Click me!' },
  'de': { 'button.label': 'Klick mich!' }
};

const getMessages = (locale) => messages[locale];

setIntlConfig({
  locales: ['en', 'de'],
  defaultLocale: 'en',
  getMessages,
});
addDecorator(withIntl);

/* eslint global-require: 0 */
const req = require.context('../app/components/', true, /stories\/.*\.js$/);

function loadStories() {
    req.keys().forEach(req)
}

configure(loadStories, module)
```

**Comment by floriangosse** [comment]
Thanks. Could you please enable the down panel and try it again?

**Comment by floriangosse** [comment]
Btw. did you add the following line to your `addon.js` file?
```
import 'storybook-addon-intl/register';
```

**Comment by floriangosse** [comment]
@diablourbano do you still have the problem?

**Comment by diablourbano** [comment]
@floriangosse sorry for the late response, yesterday I did something that make them appear, it's kind of weir though.

If the panel is at the right, instead of the bottom, the buttons appear. 🤔

**Comment by floriangosse** [comment]
Okay. I will try to reproduce it with different positions of the panel.

**Comment by floriangosse** [comment]
Sorry for the delay. I tried to show the locale switcher in the right panel and for me it worked with the following options:
```js
setOptions({
    downPanelInRight: true
});
```

**Comment by raykudo** [comment]
> If the panel is at the right, instead of the bottom, the buttons appear. 🤔

> setOptions({
    downPanelInRight: true
});

this does not work for me.  Buttons still dono't appear...

**Comment by raykudo** [comment]
![2017-11-29 11 39 01](https://user-images.githubusercontent.com/11305266/33358239-ef50e4aa-d4f9-11e7-99e7-1b589a7d9784.png)

**Comment by raykudo** [comment]
![2017-11-29 11 43 49](https://user-images.githubusercontent.com/11305266/33358333-990ff1ac-d4fa-11e7-836d-8ecd37b696d6.png)

> If the panel is at the right, instead of the bottom, the buttons appear. 🤔

> setOptions({
downPanelInRight: true
});

this does not work for me. Buttons still don't appear...

**Comment by raykudo** [comment]
Once I clicked `Locales` buttons showed up!

**Comment by floriangosse** [comment]
@raykudo could you provide your config? It might help to reproduce the issue. :)

**Comment by raykudo** [comment]
@floriangosse thanks but I found I needed to click the `Locales` on the Addons List to show the buttons up and that solves my prob :)

**Comment by floriangosse** [comment]
That's nice to hear. :)

**Comment by anselmdk** [comment]
This worked for me too, might be a good idea to point to this thread from the README

**Comment by floriangosse** [comment]
I will add this hint to the README. :)
