### ISSUE TITLE
add support for formats

### ISSUE THREAD

**Issue by Victorien-Tardif** [truffls/storybook-addon-intl#30]
It would be usefull to add a getFormats(locale) function, exactly as getMessages, to pass formats to IntlProvider

**Comment by floriangosse** [comment]
Could you share an example of this part of an app? I'd like to understand what you want to do exactly.

**Comment by Victorien-Tardif** [comment]
Yep :)
I use different formats based on locale, especially for dates and times (but also for numbers, currencies ...).
For example :

```
const formats = {
      en: {
        date: 'YYYY/MM/DD',
        datetime: 'YYYY/MM/DD hh:mm A',
        time: 'hh:mm A',
      },
      fr: {
        date: 'DD/MM/YYYY',
        datetime: 'DD/MM/YYYY HH:mm',
        time: 'HH:mm',
      },
    };
```
As for messages, they are passed to IntlProvider and can be used in components directly.

**Comment by floriangosse** [comment]
You're right. I totally forgot about this property. 😄 But I'd like to have support for it.

It would be nice if you could create a pull request for this feature. :)

**Comment by Victorien-Tardif** [comment]
Yeah, I'll try to, maybe tomorrow.

**Comment by floriangosse** [comment]
Thank you. The new version was published. :)

**Comment by Victorien-Tardif** [comment]
Thank you for you reactivity :)
