### ISSUE TITLE
Dynamic language loading

### ISSUE THREAD

**Issue by davidsamacoits** [truffls/storybook-addon-intl#39]
Looks like there is no way (or at least I couldn't find one) to provide a specific language for a specific story.
Let's say I was to display a story in English and then the same one in French. How would I do it?
Because when I'm adding my decorator it's for the entire Storybook, and I can't change it afterwards without affecting the entire application.
Thanks for your help.

**Comment by floriangosse** [comment]
That's an interesting idea. Since we can pass options to stories this shouldn't be  too hard to do.

Are you interested in submitting a PR for this feature?

**Comment by davidsamacoits** [comment]
Unfortunately pretty busy at the moment but I'll submit something if I figure a nice way to solve this problem

**Comment by floriangosse** [comment]
This works now in the new version of storybook-addon-intl. You can configure the addon on a per story bases. Please check it out.
