### ISSUE TITLE
Does not work in IE 11

### ISSUE THREAD

**Issue by jannnik** [truffls/storybook-addon-intl#44]
After upgrading react-intl to 3.x, my storybook stopped working in IE 11. It seems to be the same bug as  documented in this issue: https://github.com/formatjs/react-intl/issues/1486

I solved the problem by removing storybook-addon-intl from the addons.js file and using IntlProvider instead, but I'm wondering if I can solve the problem differently and keep storybook-addon-intl.

My setup: latest Create-React-App with typescript, latest Storybook, latest react-intl

**Comment by Zhouzi** [comment]
From my understanding, this issue comes from the fact that react-intl is publishing non-transpiled file. The suggested solution is to tweak the webpack config, which is not possible without ejecting from create-react-app. I'm still hoping to find a solution that doesn't include ejecting though.
