### ISSUE TITLE
Keep language in new tab

### ISSUE THREAD

**Issue by florian-sander** [truffls/storybook-addon-intl#45]
It would be great if the currently selected language would be used when the canvas is opened in a new tab. Currently, there does not seem to be a way to use anything but the default language in new tabs.

Context: I am using Storybook to create screenshots of my app. Obviously I don't want the Storybook interface in the screenshots, so I'm opening each story in a new tab. So I have to change the default language if I want to take screenshots in other languages.

If issue #39 gets implemented my use case would be solved as well since I could create separate stories for each language. It would be a bit of a workaround though since not all my stories currently require a separate story for each language.

Other than that: Great addon! Thanks for the fabulous work!

**Comment by floriangosse** [comment]
This works now in the new version of storybook-addon-intl. Please check it out.
