### ISSUE TITLE
Accept 'getMessages' that returns a Promise

### ISSUE THREAD

**Issue by matteocng** [truffls/storybook-addon-intl#9]
We could also accept a `getMessages` that returns a Promise, allowing people who fetch messages from a `REST API` to use them when developing the components in Storybook.

To add this feature we may need to resolve the Promise inside [WithIntl](https://github.com/truffls/storybook-addon-intl/blob/master/src/preview/containers/WithIntl/index.js) (when the component is mounted and every time the locale is switched), putting the fetched messages into the state and thus triggering a re-render (that would pass the messages to `IntlProvider`).

**Comment by floriangosse** [comment]
What about fetching the messages from the server before you will start storybook. This will avoid many requests to your server which provides the messages.

**Comment by tmaciej** [comment]
@floriangosse could you possibly provide an example of how to do it? I tried calling storybook `configure` function from within a promise handler but couldn't get it to work.

**Comment by matteocng** [comment]
@floriangosse sorry for the late reply, I've [given it a try](https://github.com/matteocng/storybook-fetch-messages-task-example) and it's a good solution because it doesn't require modifying this package and the API(s) are called only once before starting `storybook`.

The solution we have been using instead it's an ES6 class component (`storybook` decorator) that 1) listens to `EVENT_SET_LOCALE_ID` and `EVENT_GET_LOCALE_ID` 2) calls our  private messages `API` and `setIntlConfig` in the constructor 3) passes the messages to `IntlProvider` in`render()`. It allows us to pick up updates to the messages in real-time and use the `LOCALES` bar to switch locales. If you think these modifications could be merged I may apply them to the codebase and submit a PR when I have time.

@tmaciej I tried too, but there is no support for that kind of async in `storybook` as far as I know. I recommend taking a look at the [storybook-fetch-messages-task-example](https://github.com/matteocng/storybook-fetch-messages-task-example).

**Comment by tmaciej** [comment]
@matteocng thanks for example. I ultimately solved it by wrapping `withIntl` decorator with another decorator that fetches messages on mount and doesn't render anything until it's done, kinda messy but it gets job done.

**Comment by floriangosse** [comment]
I tried it out with a `setTimeout` and it worked:
```
setTimeout(() => {
    configure(loadStories, module);
}, 4000);
```

**Comment by floriangosse** [comment]
@matteocng does it work for you now?
